In [1]:
import numpy as np
#Dizileri dikey olarak birleştirme

In [2]:
a = np.zeros(20).reshape(2, -1)#Diziyi 2 satır haline getirir '-1' eşit 2 satır olması anlamına gelir
b = np.repeat(1,20).reshape(2, -1)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [3]:
b

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [4]:
np.vstack([a,b])#Dikey olarak dizileri birleştirmek

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:
a1 = np.array([[1],[2],[3]])
b1 = np.array([[4],[5],[6]])
a1

array([[1],
       [2],
       [3]])

In [6]:
b1

array([[4],
       [5],
       [6]])

In [7]:
np.vstack([a1,b1])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [8]:
#Dizileri yatay olarak birleştirme

In [9]:
np.hstack([a1,b1])#Yatay olarak dizileri birleştiren fonksiyon vstack ile aynı kullanım

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
np.hstack([a,b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [11]:
c1 = np.array([10,20,30,40,50,60])
c2 = np.array([12,20,34,49,50,65])

In [12]:
np.intersect1d(c1,c2)#Dizilerdeki benzer elemanları bulan fonksiyon

array([20, 50])

In [13]:
np.setdiff1d(c1,c2)#Ortak elemanları çıkarıp geriye kalanları bulan fonksiyon

array([10, 30, 40, 60])

In [14]:
a1 = np.arange(0,60)
a1[np.where((a1 > 20) & (a1 < 35))]#koşul vermek

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [15]:
a1 = np.arange(0,60)
a1[np.where((a1 > 20) & (a1 < 35) | (a1 % 10 == 0))]

array([ 0, 10, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       40, 50])

In [16]:
a1[np.where(np.logical_or(np.logical_and(a1 > 20, a1 < 35),(a1 % 10 == 0)))]
#and işareti yerine logical_and fonksiyonu kullanılabilir
#or işareti yerine logical_or fonksiyonu kullanılabilir

array([ 0, 10, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       40, 50])

In [17]:
#Ters alma
a4 = np.arange(10,30)

In [18]:
a4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [19]:
a4[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [20]:
np.flip(a4)#Tersini alma fonksiyonları

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [21]:
a3 = np.array([[3,2,8,1],[70,80,12,31],[12,34,16,78]])

In [22]:
a3

array([[ 3,  2,  8,  1],
       [70, 80, 12, 31],
       [12, 34, 16, 78]])

In [23]:
np.flip(a3)

array([[78, 16, 34, 12],
       [31, 12, 80, 70],
       [ 1,  8,  2,  3]])

In [24]:
a3[::-1,]

array([[12, 34, 16, 78],
       [70, 80, 12, 31],
       [ 3,  2,  8,  1]])

In [25]:
#Sıralama
a = np.array([43,123,441,51,13,101,16,73,148])
np.sort(a) # artan sıralama

array([ 13,  16,  43,  51,  73, 101, 123, 148, 441])

In [26]:
b = np.sort(a)
b = b[::-1]

In [27]:
b

array([441, 148, 123, 101,  73,  51,  43,  16,  13])

In [28]:
c = np.sort(a)
np.flip(c)

array([441, 148, 123, 101,  73,  51,  43,  16,  13])

In [29]:
a[::-1].sort()
a

array([441, 148, 123, 101,  73,  51,  43,  16,  13])

In [30]:
p4 = np.loadtxt('sample.txt', dtype = np.integer)
p4

array([[24, 29, 88],
       [ 1,  0,  8],
       [33,  7, 99],
       [39, 11, 98],
       [22, 76, 87]])

In [31]:
p5 = np.genfromtxt('sample0.txt', dtype='str')
p5

array([['Dogu', 'Turkey', 'Football'],
       ['John', 'USA', 'Hockey'],
       ['Paul', 'Canada', 'Basketball']], dtype='<U10')